apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appset-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: testns
  # Add a this finalizer ONLY if you want these to cascade delete.
spec:
  # The project the application belongs to.
  project: default
  source:
    repoURL: https://github.com/nasirudheen/my-apps.git 
    targetRevision: main 
    path: apps
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: testns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
