apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
spec:
  generators:
  - git:
      repoURL: https://github.com/nasirudheen/my-argo.git 
      revision: HEAD
      files:
      - path: "apps/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}'
    spec:
      project: default 

#      source:
#        helm:
#          valueFiles:
#            - 'values.{{tenant.id}}.yaml'
#        path: 'tenants/{{tenant.id}}'
#        repoURL: 'https://github.com/xsreality/argocd-applicationset-demo.git'
#        targetRevision: main

      source:
        helm:
          valueFiles:
            - '{{cluster.name}}/values.yaml'
              
        repoURL: https://github.com/nasirudheen/my-apps.git 
        targetRevision: main
        path: 'apps/{{cluster.name}}'
      destination:
        name: '{{cluster.name}}'  # cluster is restricted
        name: '{{cluster.name}}'  # cluster is restricted
#        server: '{{cluster.address}}'
        server: https://192.168.20.1:6443
        namespace: default  # namespace is restricted

