apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
spec:
  generators:
  - git:
      repoURL: https://github.com/nasirudheen/my-argo.git 
      revision: main
      files:
      - path: "apps/**/config.json"
  template:
    metadata:
      name: '{{tenant.name}}'
    spec:
      project: default 
      source:
        helm:
          valueFiles:
            - 'values.yaml'
              
        repoURL: https://github.com/nasirudheen/my-apps.git 
        targetRevision: main
        path: 'apps/{{tenant.name}}'

      destination:
        name: '{{tenant.name}}'  # cluster is restricted
#        server: '{{cluster.address}}'
        server: https://192.168.122.11:6443
        namespace: testns  # namespace is restricted
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
   
